[package]
name = "axum-subdomain-routing"
version = "0.0.8"
edition = "2024"


authors = ["Erdem Göksel <erdem.goksel.dev@gmail.com>"]
description = "A high-performance subdomain routing library for Axum framework in Rust."
license = "MIT"
repository = "https://github.com/ErdemGKSL/axum-subdomain-routing"  
homepage = "https://github.com/ErdemGKSL/axum-subdomain-routing"
documentation = "https://docs.rs/axum-subdomain-routing"
readme = "README.md"
keywords = ["axum", "subdomain", "routing", "rust", "web"]
categories = ["web-programming", "network-programming"]


[dependencies]
axum = "0.8.7"
tower = { version = "0.5.2", features = ["util"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
